spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students-db?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: my-sql
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration